<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StudentSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('students')->insert([
            // SICT Students
            [
                'pb_student_code' => '24FTT001',
                'user_id' => 2,
                'full_name' => 'Ahmad Haziq Bin Rahman',
                'ic_number' => '01-123456',
                'ic_colour' => 'Yellow',
                'programme_id' => 1,
                'intake_session' => 'July 2024',
                'postal_address' => 'No. 123, Jalan Gadong, Bandar Seri Begawan',
                'date_of_birth' => '2003-05-10',
                'place_of_birth' => 'RIPAS Hospital',
                'gender' => 'Male',
                'religion' => 'Islam',
                'nationality' => 'Bruneian',
                'race' => 'Malay',
                'mobile_phone' => '87341234',
                'cgpa' => 2.40,
                'work_experience' => 'Part-time retail assistant at Gadong Mall (2023)',
                'emergency_no' => '87654321',
                'cv_file_path' => '/storage/cv/ahmad_haziq.pdf',
                'vetting_status' => 'Approved',
                'created_at' => now()
            ],
            [
                'pb_student_code' => '24FTT002',
                'user_id' => 3,
                'full_name' => 'Sarah Binti Ali',
                'ic_number' => '01-654321',
                'ic_colour' => 'Red',
                'programme_id' => 2,
                'intake_session' => 'July 2024',
                'postal_address' => 'No. 45, Spg 32, Jalan Muara',
                'date_of_birth' => '2003-08-15',
                'place_of_birth' => 'Pengiran Isteri Hajah Mariam Hospital',
                'gender' => 'Female',
                'religion' => 'Islam',
                'nationality' => 'Bruneian',
                'race' => 'Malay',
                'mobile_phone' => '88765432',
                'cgpa' => 2.30,
                'work_experience' => null,
                'emergency_no' => '87651234',
                'cv_file_path' => '/storage/cv/sarah_ali.pdf',
                'vetting_status' => 'Pending',
                'created_at' => now()
            ],
            [
                'pb_student_code' => '24FTT003',
                'user_id' => 4,
                'full_name' => 'John Lim Wei Meng',
                'ic_number' => '01-999888',
                'ic_colour' => 'Purple',
                'programme_id' => 3,
                'intake_session' => 'July 2024',
                'postal_address' => 'No. 78, Jalan Kiulap',
                'date_of_birth' => '2002-11-20',
                'place_of_birth' => 'Gleneagles JPMC',
                'gender' => 'Male',
                'religion' => 'Buddhist',
                'nationality' => 'Bruneian',
                'race' => 'Chinese',
                'mobile_phone' => '89887766',
                'cgpa' => 2.75,
                'work_experience' => 'Intern at TelBru (Summer 2023)',
                'emergency_no' => '87659876',
                'cv_file_path' => '/storage/cv/john_lim.pdf',
                'vetting_status' => 'Approved',
                'created_at' => now()
            ],
            // SBA Students
            [
                'pb_student_code' => '24FTB001',
                'user_id' => 5,
                'full_name' => 'Nurul Aisyah Binti Hassan',
                'ic_number' => '02-456789',
                'ic_colour' => 'Yellow',
                'programme_id' => 5,
                'intake_session' => 'July 2024',
                'postal_address' => 'No. 67, Kampong Kiulap',
                'date_of_birth' => '2003-02-20',
                'place_of_birth' => 'RIPAS Hospital',
                'gender' => 'Female',
                'religion' => 'Islam',
                'nationality' => 'Bruneian',
                'race' => 'Malay',
                'mobile_phone' => '88771234',
                'cgpa' => 3.00,
                'work_experience' => 'Part-time admin assistant at Bank Islam Brunei Darussalam',
                'emergency_no' => '87659876',
                'cv_file_path' => '/storage/cv/nurul_aisyah.pdf',
                'vetting_status' => 'Approved',
                'created_at' => now()
            ],
            [
                'pb_student_code' => '24FTB002',
                'user_id' => 6,
                'full_name' => 'Mohammad Faiz Bin Osman',
                'ic_number' => '02-789123',
                'ic_colour' => 'Red',
                'programme_id' => 6,
                'intake_session' => 'July 2024',
                'postal_address' => 'No. 89, Jalan Tutong',
                'date_of_birth' => '2003-07-11',
                'place_of_birth' => 'Tutong Hospital',
                'gender' => 'Male',
                'religion' => 'Islam',
                'nationality' => 'Bruneian',
                'race' => 'Malay',
                'mobile_phone' => '89882345',
                'cgpa' => 3.00,
                'work_experience' => null,
                'emergency_no' => '87771234',
                'cv_file_path' => '/storage/cv/faiz_osman.pdf',
                'vetting_status' => 'Pending',
                'created_at' => now()
            ],
            // SSE Student
            [
                'pb_student_code' => '24FTE001',
                'user_id' => 7,
                'full_name' => 'Lim Wei Jie',
                'ic_number' => '03-567890',
                'ic_colour' => 'Purple',
                'programme_id' => 9,
                'intake_session' => 'July 2024',
                'postal_address' => 'No. 234, Jalan Berakas',
                'date_of_birth' => '2002-12-05',
                'place_of_birth' => 'Jerudong Park Medical Centre',
                'gender' => 'Male',
                'religion' => 'Buddhist',
                'nationality' => 'Bruneian',
                'race' => 'Chinese',
                'mobile_phone' => '89772345',
                'cgpa' => 2.60,
                'work_experience' => 'Workshop assistant at Shell Brunei',
                'emergency_no' => '87652345',
                'cv_file_path' => '/storage/cv/lim_weijie.pdf',
                'vetting_status' => 'Approved',
                'created_at' => now()
            ],
            // SHS Student
            [
                'pb_student_code' => '24FTH001',
                'user_id' => 8,
                'full_name' => 'Siti Nurhaliza Binti Abdullah',
                'ic_number' => '04-345678',
                'ic_colour' => 'Yellow',
                'programme_id' => 13,
                'intake_session' => 'July 2024',
                'postal_address' => 'No. 56, Kampong Ayer',
                'date_of_birth' => '2003-03-15',
                'place_of_birth' => 'Pengiran Isteri Hajah Mariam Hospital',
                'gender' => 'Female',
                'religion' => 'Islam',
                'nationality' => 'Bruneian',
                'race' => 'Malay',
                'mobile_phone' => '88774567',
                'cgpa' => 2.50,
                'work_experience' => 'Volunteer at RIPAS Hospital (2023)',
                'emergency_no' => '87653456',
                'cv_file_path' => '/storage/cv/siti_nurhaliza.pdf',
                'vetting_status' => 'Approved',
                'created_at' => now()
            ],
        ]);
    }
}
